"""Recommendations generated by the agent decision engine."""
from datetime import datetime

from sqlalchemy import String, DateTime, ForeignKey, func
from sqlalchemy.orm import Mapped, mapped_column

from app.database import Base


class Recommendation(Base):
    __tablename__ = "recommendations"

    id: Mapped[int] = mapped_column(primary_key=True)
    report_id: Mapped[int] = mapped_column(ForeignKey("crop_reports.id"), index=True)
    recommendation: Mapped[str] = mapped_column(String(500))
    priority: Mapped[str] = mapped_column(String(20), default="MEDIUM")  # LOW/MEDIUM/HIGH/CRITICAL
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
